### PR TITLE
Upgrade Go to 1.22

### PR DESCRIPTION
**Pull request by zegerius**
*Description of changes:*

This PR:

- upgrades Go to 1.22, as [EOL of 1.13 was August 11, 2020](https://versionlog.com/golang/1.13/)
- upgrades go-git to v5, as v4 has not been updated [since Mar 15, 2020](https://github.com/go-git/go-git/releases/tag/v5.0.0). The v5 release did not introduce any breaking changes to the API.
- removes `xerrors` in favor of `errors.New` and `fmt.Errorf`, as [this functionality has been part of stdlib since 1.13](https://pkg.go.dev/golang.org/x/xerrors).

This PR does not introduce any breaking changes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zegerius** [comment]
Hi @knqyf263, as we use this tool in several CI flows I wanted to see if I can contribute some of my time to improve it. I noticed cob is still using Go 1.13. Hope you appreciate the contribution here and in https://github.com/knqyf263/cob/pull/65.

**Comment by knqyf263** [comment]
Thanks for your contribution.

>These functions were incorporated into the standard library's errors package in Go 1.13: - Is - As - Unwrap

xerrors.Errorf is not deprecated.

**Comment by zegerius** [comment]
> xerrors.Errorf is not deprecated.

Rephrased :)

**Comment by knqyf263** [comment]
I mean it's needed for stack trace.

**Comment by zegerius** [comment]
If I understand correctly you want to use the stack backtrace that xerrors provides? I see [the Go team removed the deprecation notice](https://groups.google.com/g/golang-codereviews/c/s4qpa8G_ew4?pli=1). I guess I can drop that change if you prefer. Wonder if it really adds any value - there's not that much special that can go wrong here.

**Comment by knqyf263** [comment]
>Wonder if it really adds any value - there's not that much special that can go wrong here.

I'm curious why you're wondering. There are many cases where it fails and stack trace can help.

**Comment by zegerius** [comment]
In this project the scope is so limited - you are running two commands and compare results. Good error handling and logging should IMO negate the introduction of a new dependency to inspect a stack.

But, I can tell you are convinced it adds value, so I'll remove the change from the PR

**Comment by knqyf263** [comment]
>In this project the scope is so limited - it is running two commands and compare results.

I don't mind if you want to delete it, but it is not because it is deprecated and it should be made clear that there is a price to pay for losing stack traces. In other words, it is better to do it in another PR if you want.

**Review by knqyf263 — APPROVED** [review]
Thanks

**Pull request merged**
